name: RDS Alterado - Remote DevOps Station
description: |
  This container runs using Ubuntu:14.04 old edition, and have the entire devops environment inside. This container can be used via URL:xxxx, and all the functions that you have on your terminal, now is available in your web terminal. 
version: "1.0"
category: CLOUD AUTOMATION
maintainer: Eric Hans <e-mail-nao-divulgado@gmail.com>
